import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Image as ImageIcon } from 'lucide-react';
import FullWindowDropZone from '../FullWindowDropZone';

const ImageConverterTool: React.FC = () => {
  const { t } = useTranslation();
  const [convertFile, setConvertFile] = useState<File | null>(null);
  const [convertPreview, setConvertPreview] = useState<string | null>(null);
  const [convertFormat, setConvertFormat] = useState<'rgb565' | 'gray'>('rgb565');
  const [convertByteOrder, setConvertByteOrder] = useState<'big' | 'little'>('big');
  const [convertCode, setConvertCode] = useState<string>('');
  const [isConverting, setIsConverting] = useState(false);

  const handleConvertFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];
      setConvertFile(file);
      setConvertPreview(URL.createObjectURL(file));
      setConvertCode('');
    }
  };

  const handleConvertDrop = (files: FileList) => {
    const file = Array.from(files).find((f) => f.type.startsWith('image/'));
    if (file) {
      setConvertFile(file);
      setConvertPreview(URL.createObjectURL(file));
      setConvertCode('');
    }
  };

  const processImage = async () => {
    if (!convertFile || !convertPreview) return;
    setIsConverting(true);

    try {
      const img = new Image();
      img.src = convertPreview;
      await new Promise((resolve) => { img.onload = resolve; });

      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('Canvas context failed');

      ctx.drawImage(img, 0, 0);
      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      const data = imageData.data;

      let output: number[] = [];

      if (convertFormat === 'rgb565') {
        for (let i = 0; i < data.length; i += 4) {
          const r = data[i];
          const g = data[i + 1];
          const b = data[i + 2];
          const rgb = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
          if (convertByteOrder === 'big') {
            output.push((rgb >> 8) & 0xFF);
            output.push(rgb & 0xFF);
          } else {
            output.push(rgb & 0xFF);
            output.push((rgb >> 8) & 0xFF);
          }
        }
      } else if (convertFormat === 'gray') {
        for (let i = 0; i < data.length; i += 4) {
          const y = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
          output.push(Math.round(y));
        }
      }

      const varName = convertFile.name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
      let cCode = `// Generated by LILYGO Spark\n`;
      cCode += `// Size: ${canvas.width}x${canvas.height}, Format: ${convertFormat.toUpperCase()}\n`;
      cCode += `const uint8_t ${varName}[] = {\n`;

      for (let i = 0; i < output.length; i++) {
        if (i % 12 === 0) cCode += '    ';
        cCode += `0x${output[i].toString(16).padStart(2, '0').toUpperCase()}`;
        if (i < output.length - 1) cCode += ', ';
        if ((i + 1) % 12 === 0) cCode += '\n';
      }
      cCode += '\n};\n';

      setConvertCode(cCode);
    } catch (e) {
      console.error(e);
      alert('Conversion failed');
    } finally {
      setIsConverting(false);
    }
  };

  return (
    <>
      <FullWindowDropZone
        active={true}
        accept="image/*"
        onDrop={handleConvertDrop}
        hintKey="common.drop_image"
      />
      <div className="flex-1 flex flex-col gap-6 overflow-hidden">
        <div className="bg-white dark:bg-slate-800 p-6 rounded-xl border border-slate-200 dark:border-slate-700 shadow-lg flex-1 flex flex-col min-h-0">
          <div className="flex gap-6 h-full">
            <div className="w-1/3 flex flex-col gap-4">
              <div className="bg-slate-100 dark:bg-slate-900 rounded-lg p-4 border border-slate-200 dark:border-slate-700 flex-1 flex flex-col items-center justify-center relative overflow-hidden">
                {convertPreview ? (
                  <img src={convertPreview} alt="Preview" className="max-w-full max-h-full object-contain" />
                ) : (
                  <div className="text-slate-500 flex flex-col items-center">
                    <ImageIcon size={48} className="mb-2 opacity-50" />
                    <span>No Image Selected</span>
                  </div>
                )}
                <input
                  type="file"
                  onChange={handleConvertFileSelect}
                  className="absolute inset-0 opacity-0 cursor-pointer"
                  accept="image/*"
                />
              </div>

              <div className="space-y-3">
                <div>
                  <label className="text-xs text-slate-400 block mb-1">Output Format</label>
                  <select
                    value={convertFormat}
                    onChange={(e) => setConvertFormat(e.target.value as any)}
                    className="w-full bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-lg p-2 text-sm"
                  >
                    <option value="rgb565">RGB565 (16-bit Color)</option>
                    <option value="gray">Grayscale (8-bit)</option>
                  </select>
                </div>
                {convertFormat === 'rgb565' && (
                  <div>
                    <label className="text-xs text-slate-400 block mb-1">{t('utilities.byte_order')}</label>
                    <select
                      value={convertByteOrder}
                      onChange={(e) => setConvertByteOrder(e.target.value as 'big' | 'little')}
                      className="w-full bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-lg p-2 text-sm"
                    >
                      <option value="big">{t('utilities.byte_order_big')}</option>
                      <option value="little">{t('utilities.byte_order_little')}</option>
                    </select>
                  </div>
                )}
                <button
                  onClick={processImage}
                  disabled={!convertFile || isConverting}
                  className="w-full py-2 bg-primary hover:bg-primary-hover text-white rounded-lg font-medium transition-colors disabled:opacity-50"
                >
                  {isConverting ? 'Converting...' : 'Generate Code'}
                </button>
              </div>
            </div>

            <div className="flex-1 flex flex-col">
              <div className="flex justify-between items-center mb-2">
                <h3 className="text-sm font-bold text-slate-700 dark:text-slate-300">Generated C Code</h3>
                <button
                  onClick={() => navigator.clipboard.writeText(convertCode)}
                  disabled={!convertCode}
                  className="text-xs bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 text-slate-800 dark:text-white px-3 py-1 rounded transition-colors"
                >
                  Copy
                </button>
              </div>
              <textarea
                value={convertCode}
                readOnly
                className="flex-1 bg-slate-50 dark:bg-black/50 border border-slate-200 dark:border-slate-700 rounded-lg p-4 font-mono text-xs text-emerald-600 dark:text-green-400 resize-none focus:outline-none"
                placeholder="// Code will appear here..."
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ImageConverterTool;
